TRUNCATE TABLE Assets
INSERT INTO Assets VALUES 
	('grass', 'Grass', '1'),
	('desert', 'Desert', '1'),
	('water', 'Ocean', '1'),
	('rocky', 'Rocky', '1'),
	('swamp', 'Swamp', '1'),
	('unknown', 'Unknown', '1'),
	('fogowar', 'Fog of War', '1'),
	('mountains', 'Mountains', '0.8'),
	('hills', 'Hills', '0.8'),
	('forest', 'Forest', '0.8'),
	('buildings', 'Outpost', '0.8'),
	('civilisation', 'Civilisation', '0.8'),
	('flowers', 'Flowers', '0.8'),
	('abode', 'Abode', '0.8'),
	('cave', 'Cave', '0.8'),
	('ruin', 'Ruin', '0.8');

TRUNCATE TABLE USERS;
INSERT INTO USERS VALUES
	-- (USERNAME, ISADMIN, GOLD, BASTIONTURNS, HASBASTION)
	('mole', 1, 1000, 0, 0),
	('halo', 0, 0, 0, 0),
	('viridia', 0, 0, 0, 0),
	('sont', 0, 0, 0, 0),
	('vilmora', 0, 0, 0, 0),
	('fedwir', 0, 0, 0, 0),
	('krog urtle', 0, 0, 0, 0),
	('rob', 0, 0, 0, 1),
	('hestegor', 0, 0, 0, 0),
	('vesle', 0, 0, 0, 0),
	('evelyn', 0, 0, 0, 0),
	('ursula', 0, 0, 0, 0),
	('laralei', 0, 0, 0, 0),
	('botrytus', 0, 0, 0, 0),
	('chryseehk', 0, 0, 0, 0),
	('nana', 0, 0, 0, 0),
	('guest', 0, 0, 0, 0),
	('freya', 0, 0, 0, 0);


TRUNCATE TABLE ITEMTYPE;
INSERT INTO ITEMTYPE VALUES
	(1, 'Equipment'),
	(2, 'Magic Item'),
	(3, 'Scroll'),
	(4, 'Trinket'),
	(5, 'Furniture'),
	(6, 'Pet'),
	(7, 'Misc');

TRUNCATE TABLE ATTRIBUTE;
INSERT INTO ATTRIBUTE VALUES
	('Dwarvern Steel', 1, '', 1.5),
	('Shoddy', 1, '', 0.5),
	('', 1, '', 1),
	('Dwarvern Steel', 5, 'Made of the very best material money can buy. ', 1.5),
	('Masoned', 5, 'Its smooth grey stone is simple but refined. ', 0.8),
	('Ceramic', 5, 'The earthen texture adds a warmth to the room. ', 1),
	('Wooden', 5, 'It is simply crafted from soft wood. ', 0.8),
	('Clockwork', 5, 'The gears moving on its surface are mesmerizing and are in perfect time with the quiet ticking it emits. ', 2),
	('Gilded', 5, 'The gilded surface oozes luxury and charm', 2),
	('Metallic', 5, 'The steely glint feels just as futuristic as it did yesterday', 1.2),
	('Rose gold', 5, 'Feels strangely familiar... ', 1.8),
	('Sandstone', 5, 'The sandstone is roughly cut, but accented with bright red fabric. ', 1),
	('Crystal', 5, 'The piece is impossibly, one large crystal. Remarkably, not as fragile as it looks. ', 3),
	('Cabin', 5, 'The rough cut wood reminds you of a cabin in the middle of nowhere. ', 1),
	('Suspicious', 5, 'It has a tendency to move when unobserved. Breathes gently. ', 1.3),
	('Flowery', 5, 'Made of corded vines and decorated with colourful petals. Comes with care instructions for sunlight and watering. ', 1.3),
	('Leafy', 5, 'Made of vines and wide, verdant leaves. Comes with care instructions for sunlight and watering. ', 1.3),
	('Budget', 5, 'Looks like it may fall apart any moment. ', 0.3),
	('Illuminant', 5, 'Whatever it is made out of gives off a soft glow at night. ', 1.5),
	('Gothic', 5, 'For those with an inner vampire. ', 1),
	('Wax', 5, 'Made of curious hexagonal wax pellets. ', 1),
	('Frozen', 5, 'Surely it is not made of real ice...? It has yet to melt. ', 1.2),
	('Opulent', 5, 'Plushed, finely crafted and tasteful.', 2),
	('Pastel', 5, 'Painted in a soft pastel pink', 1),
	('Pastel', 5, 'Painted in a soft pastel blue', 1),
	('Pastel', 5, 'Painted in a soft pastel purple', 1),
	('Coral', 5, 'Sharp on the corners. Comes with care instructions on watering. ', 1.2),
	('Red', 5, 'Painted a simple red. ', 1),
	('Blue', 5, 'Painted a simple blue. ', 1),
	('Green', 5, 'Painted a simple green. ', 1),
	('Orange', 5, 'Painted a simple orange. ', 1),
	('Yellow', 5, 'Painted a simple yellow. ', 1),
	('Purple', 5, 'Painted a simple purple. ', 1),
	('Indigo', 5, 'Painted a simple indigo. ', 1),
	('White', 5, 'Painted a simple white. ', 1),
	('Black', 5, 'Painted a simple black. ', 1),
	('Grey', 5, 'Painted a simple grey. ', 1),
	('Steampunk', 5, 'A coppery piece that gives off hot steam occassionally. ', 1.3),
	('Glitched', 5, 'You feel uneasy looking at it. ', 100),
	('Granite', 5, 'It has a dappled red lustre. ', 1.2),
	('Obsidian', 5, 'It has a deep black colour. ', 1.3),
	('Marble', 5, 'It has a deep white pattern. ', 1.3),
	('Jade', 5, 'It has a deep green lustre. ', 1.3),
	('Feywood', 5, 'It has a tedency to move when out of view. ', 1),
	('Mahogany', 5, 'It has a deep caramel shine. ', 1),
	('Cloud', 5, 'What is this made of? You can hold it, but it looks like it is made out of fog and feels as soft as cotton. ', 1.5),
	('Fungal', 5, 'The... wood, is spongy, and the fungal caps glow a dim blue at night. ', 1),
	('Glass', 5, 'Masterfully blown from glass, you feel the need to treat it with utmost care. ', 1.3),
	('Feathered', 5, 'Brilliantly plumed with a vibrant birds feathers. ', 1.2)
	-- ('Name', 5, '', 1),

TRUNCATE TABLE RANDOMITEM;
INSERT INTO RANDOMITEM VALUES
	-- ItemID (Auto), ItemName, ItemTypeID (ItemType), ItemDescription, Price
	('Table', 5, 'A four-legged table. ', 1),
	('Armchair', 5, 'A cushioned, wide chair. ', 3),
	('Single Bed', 5, 'A functional single bed. ', 5),
	('Double Bed', 5, 'A bed fit for two humanoids (or about 1/2 a Fluffy)', 8),
	('Poster Bed', 5, 'A somewhat gradiose, four poster bed', 15),
	('Bench', 5, 'A low bench, fit to sit on. ', 2),
	('Bookshelf', 5, 'A tall bookshelf. ', 5),
	('Cabinet', 5, 'A functional set of storage. ', 6),
	('Counter', 5, 'A smooth surface for cooking or tinkering sits above some storage space. ', 6),
	('Candleabra', 5, 'It holds enough candles to keep the night away. ', 10),
	('Chandelier', 5, 'Dazzle your friends and foes alike with this ceiling fixture. ', 20),
	('Chair', 5, 'A four-legged chair. ', 0.5),
	('Lamp', 5, 'A free-standing lamp that gives off a warm light when fueled. ', 10),
	('Dresser', 5, 'For all your clothes and trinkets. ', 12),
	('Flooring', 5, 'For a change of pace. ', 10),
	('Sofa', 5, 'A wide cushioned sofa. ', 30),
	('Stool', 5, 'A three-legged stool. ', 1.5),
	('Wardrobe', 5, 'A imposing wardrobe, for your sunday best. ', 15),
	('Mirror', 5, ' A full length mirror. Look! Its you! ', 30),
	('Bathtub', 5, 'Filling may take a while but you would be the cleanest creature on the continent. ', 10),
	('Chest', 5, 'A functional chest, to be booby trapped at your leisure. ', 5),
	('Candle', 5, 'A small candle holder. ', 1),
	('Grandfather Clock', 5, 'It gives a sinister gong every hour. ', 30),
	('Sconce', 5, 'A wall mount for a oil lamp, or other light source. ', 6);