TRUNCATE TABLE Assets
INSERT INTO Assets VALUES 
	('grass', 'Grass', '1'),
	('desert', 'Desert', '1'),
	('water', 'Ocean', '1'),
	('rocky', 'Rocky', '1'),
	('swamp', 'Swamp', '1'),
	('unknown', 'Unknown', '1'),
	('fogowar', 'Fog of War', '1'),
	('mountains', 'Mountains', '0.8'),
	('hills', 'Hills', '0.8'),
	('forest', 'Forest', '0.8'),
	('buildings', 'Outpost', '0.8'),
	('civilisation', 'Civilisation', '0.8'),
	('flowers', 'Flowers', '0.8'),
	('abode', 'Abode', '0.8'),
	('cave', 'Cave', '0.8'),
	('ruin', 'Ruin', '0.8');

TRUNCATE TABLE USERS;
INSERT INTO USERS VALUES
	-- (USERNAME, ISADMIN, GOLD, BASTIONTURNS, HASBASTION)
	('mole', 1, 1000, 0, 0),
	('halo', 0, 0, 0, 0),
	('viridia', 0, 0, 0, 0),
	('sont', 0, 0, 0, 0),
	('vilmora', 0, 0, 0, 0),
	('fedwir', 0, 0, 0, 0),
	('krog urtle', 0, 0, 0, 0),
	('rob', 0, 0, 0, 1),
	('hestegor', 0, 0, 0, 0),
	('vesle', 0, 0, 0, 0),
	('evelyn', 0, 0, 0, 0),
	('ursula', 0, 0, 0, 0),
	('laralei', 0, 0, 0, 0),
	('botrytus', 0, 0, 0, 0),
	('chryseehk', 0, 0, 0, 0),
	('nana', 0, 0, 0, 0),
	('guest', 0, 0, 0, 0),
	('freya', 0, 0, 0, 0);


-- TRUNCATE TABLE ITEMTYPE;
INSERT INTO ITEMTYPE VALUES
	(1, 'Equipment'),
	(2, 'Magic Item'),
	(3, 'Scroll'),
	(4, 'Trinket'),
	(5, 'Furniture'),
	(6, 'Pet'),
	(7, 'Misc');

TRUNCATE TABLE ATTRIBUTE;
INSERT INTO ATTRIBUTE VALUES
	('Dwarvern Steel', 1, '', 1.5),
	('Shoddy', 1, '', 0.5),
	('', 1, '', 1),
	('Dwarvern Steel', 5, 'Made of the very best material money can buy. ', 1.5),
	('Masoned', 5, 'Its smooth grey stone is simple but refined. ', 0.8),
	('Ceramic', 5, 'The earthen texture adds a warmth to the room. ', 1),
	('Wooden', 5, 'It is simply crafted from soft wood. ', 0.8),
	('Clockwork', 5, 'The gears moving on its surface are mesmerizing and are in perfect time with the quiet ticking it emits. ', 2),
	('Gilded', 5, 'The gilded surface oozes luxury and charm', 2),
	('Metallic', 5, 'The steely glint feels just as futuristic as it did yesterday', 1.2),
	('Rose gold', 5, 'Feels strangely familiar... ', 1.8),
	('Sandstone', 5, 'The sandstone is roughly cut, but accented with bright red fabric. ', 1),
	('Crystal', 5, 'The piece is impossibly, one large crystal. Remarkably, not as fragile as it looks. ', 3),
	('Cabin', 5, 'The rough cut wood reminds you of a cabin in the middle of nowhere. ', 1),
	('Suspicious', 5, 'It has a tendency to move when unobserved. Breathes gently. ', 1.3),
	('Flowery', 5, 'Made of corded vines and decorated with colourful petals. Comes with care instructions for sunlight and watering. ', 1.3),
	('Leafy', 5, 'Made of vines and wide, verdant leaves. Comes with care instructions for sunlight and watering. ', 1.3),
	('Budget', 5, 'Looks like it may fall apart any moment. ', 0.3),
	('Illuminant', 5, 'Whatever it is made out of gives off a soft glow at night. ', 1.5),
	('Gothic', 5, 'For those with an inner vampire. ', 1),
	('Wax', 5, 'Made of curious hexagonal wax pellets. ', 1),
	('Frozen', 5, 'Surely it is not made of real ice...? It has yet to melt. ', 1.2),
	('Opulent', 5, 'Plushed, finely crafted and tasteful.', 2),
	('Pastel', 5, 'Painted in a soft pastel pink', 1),
	('Pastel', 5, 'Painted in a soft pastel blue', 1),
	('Pastel', 5, 'Painted in a soft pastel purple', 1),
	('Coral', 5, 'Sharp on the corners. Comes with care instructions on watering. ', 1.2),
	('Red', 5, 'Painted a simple red. ', 1),
	('Blue', 5, 'Painted a simple blue. ', 1),
	('Green', 5, 'Painted a simple green. ', 1),
	('Orange', 5, 'Painted a simple orange. ', 1),
	('Yellow', 5, 'Painted a simple yellow. ', 1),
	('Purple', 5, 'Painted a simple purple. ', 1),
	('Indigo', 5, 'Painted a simple indigo. ', 1),
	('White', 5, 'Painted a simple white. ', 1),
	('Black', 5, 'Painted a simple black. ', 1),
	('Grey', 5, 'Painted a simple grey. ', 1),
	('Steampunk', 5, 'A coppery piece that gives off hot steam occassionally. ', 1.3),
	('Glitched', 5, 'You feel uneasy looking at it. ', 100),
	('Granite', 5, 'It has a dappled red lustre. ', 1.2),
	('Obsidian', 5, 'It has a deep black colour. ', 1.3),
	('Marble', 5, 'It has a deep white pattern. ', 1.3),
	('Jade', 5, 'It has a deep green lustre. ', 1.3),
	('Feywood', 5, 'It has a tedency to move when out of view. ', 1),
	('Mahogany', 5, 'It has a deep caramel shine. ', 1),
	('Cloud', 5, 'What is this made of? You can hold it, but it looks like it is made out of fog and feels as soft as cotton. ', 1.5),
	('Fungal', 5, 'The... wood, is spongy, and the fungal caps glow a dim blue at night. ', 1),
	('Glass', 5, 'Masterfully blown from glass, you feel the need to treat it with utmost care. ', 1.3),
	('Feathered', 5, 'Brilliantly plumed with a vibrant birds feathers. ', 1.2)
	-- ('Name', 5, '', 1),

TRUNCATE TABLE RANDOMITEM;
INSERT INTO RANDOMITEM VALUES
	-- ItemID (Auto), ItemName, ItemTypeID (ItemType), ItemDescription, Price
	-- 1. Equipment
	('Padded Light Armour', 1, 'AC 11 + DEX, but disadvantage on stealth checks. ', 5),
	('Leather Light Armour', 1, 'AC 11 + DEX. ', 10),
	('Studded Leather Armour', 1, 'AC 12 + DEX. ', 45),
	('Hide Medium Armour', 1, 'AC 12 + (DEX, max of 2)', 10),
	('Chain Medium Armour', 1, 'AC 13 + (DEX, max of 2)', 50),
	('Scale Medium Armour', 1, 'AC 14 + (DEX, max of 2), but disadvantage on stealth checks. ', 50),
	('Breastplate Medium Armour', 1, 'AC 14 + (DEX, max of 2)', 400),
	('Half Plate Medium Armour', 1, 'AC 15 + (DEX, max of 2), but disadvantage on stealth checks. ', 750),
	('Ring Mail Heavy Armour', 1, 'AC 14, but disadvantage on stealth checks. ', 30),
	('Chain Mail Heavy Armour', 1, 'AC 16, but disadvantage on stealth checks. ', 75),
	('Splint Heavy Armour', 1, 'AC 17, but disadvantage on stealth checks. ', 200),
	('Plate Heavy Armour', 1, 'AC 18, but disadvantage on stealth checks. ', 1500),
	('Shield', 1, 'Grants +2 AC while held', 10),
	('Club', 1, '1d4 bludgeoning. Light. ', 0.1),
	('Dagger', 1, '1d4 piercing. Finesse, light, thrown. ', 2),
	('Greatclub', 1, '1d8 bludgeoning. Two-handed. ', 0.2),
	('Handaxe', 1, '1d6 slashing. Light, thrown. ', 0.5),
	('Javelin', 1, '1d6 piercing. Thrown. ', 0.5),
	('Light Hammer', 1, '1d4 bludgeoning. Light, thrown. ', 2),
	('Mace', 1, '1d6 bludgeoning', 5),
	('Quarter Staff', 1, '1d6 bludgeoning. Versatile. ', 0.2),
	('Sickle', 1, '1d4 slashing. Light. ', 1),
	('Spear', 1, '1d6 piercing. Thrown. ', 1),
	('Light Crossbow', 1, '1d8 piercing. ', 25),
	('Dart', 1, '1d4 piercing. Finesse, thrown. ', 0.05),
	('Shortbow', 1, 'Please consult the relevant weapons stats. ', 25),
	('Sling', 1, 'Please consult the relevant weapons stats. ', 0.1),
	('Battleaxe', 1, 'Please consult the relevant weapons stats. ', 10),
	('Flail', 1, 'Please consult the relevant weapons stats. ', 10),
	('Glaive', 1, 'Please consult the relevant weapons stats. ', 20),
	('Greataxe', 1, 'Please consult the relevant weapons stats. ', 30),
	('Greatsword', 1, 'Please consult the relevant weapons stats. ', 50),
	('Halberd', 1, 'Please consult the relevant weapons stats. ', 20),
	('Lance', 1, 'Please consult the relevant weapons stats. ', 10),
	('Longsword', 1, 'Please consult the relevant weapons stats. ', 15),
	('Maul', 1, 'Please consult the relevant weapons stats. ', 10),
	('Morningstar', 1, 'Please consult the relevant weapons stats. ', 15),
	('Pike', 1, 'Please consult the relevant weapons stats. ', 5),
	('Rapier', 1, 'Please consult the relevant weapons stats. ', 25),
	('Scimitar', 1, 'Please consult the relevant weapons stats. ', 25),
	('Shortsword', 1, 'Please consult the relevant weapons stats. ', 10),
	('Trident', 1, 'Please consult the relevant weapons stats. ', 5),
	('War Pick', 1, 'Please consult the relevant weapons stats. ', 5),
	('Warhammer', 1, 'Please consult the relevant weapons stats. ', 15),
	('Whip', 1, 'Please consult the relevant weapons stats. ', 2),
	('Blowgun', 1, 'Please consult the relevant weapons stats. ', 10),
	('Hand Crossbow', 1, 'Please consult the relevant weapons stats. ', 75),
	('Heavy Crossbow', 1, 'Please consult the relevant weapons stats. ', 50),
	('Longbow', 1, 'Please consult the relevant weapons stats. ', 50),
	('Net', 1, 'Please consult the relevant weapons stats. ', 1),
	('Arcane Focus: Crystal', 1, 'Please consult the relevant weapons stats. ', 1),
	('Arcane Focus: Orb', 1, 'Please consult the relevant weapons stats. ', 1),
	('Arcane Focus: Rod', 1, 'Please consult the relevant weapons stats. ', 1),
	('Arcane Focus: Staff', 1, 'Please consult the relevant weapons stats. ', 1),
	('Arcane Focus: Wand', 1, 'Please consult the relevant weapons stats. ', 1),
	('Abacus', 1, 'For counting. ', 2),
	('Acid (vial)', 1, 'Check item description in player handbook', 25),
	('Alchemists fire (flask)', 1, 'Check item description in player handbook', 50),
	('Antitoxin (vial)', 1, 'Check item description in player handbook', 50),
	('Ball bearings (bag of 1,000)', 1, 'Check item description in player handbook', 1),
	('Basket', 1, 'Check item description in player handbook', 0.4),
	('Bedroll', 1, 'Check item description in player handbook', 1),
	('Bell', 1, 'Channel your inner town crier. ', 1),
	('Blanket', 1, 'Check item description in player handbook', 0.5),
	('Block and tackle', 1, 'Check item description in player handbook', 1),
	('Book', 1, 'Check item description in player handbook', 25),
	('Bottle, glass', 1, 'Check item description in player handbook', 2),
	('Bucket', 1, 'Demand is high, strike while the iron is hot. ', 0.05),
	('Caltrops (bag of 20)', 1, 'Check item description in player handbook', 1),
	('Candle', 1, 'Romantic. ', 0.01),
	('Map scroll case', 1, 'For all your treasure maps', 1),
	('Chain (10 feet)', 1, 'Check item description in player handbook', 5),
	('Chalk (1 piece)', 1, 'Check item description in player handbook', 0.01),
	('Climbers kit', 1, 'Check item description in player handbook', 25),
	('Clothes, costume', 1, 'Colourful, yet gauche. ', 5),
	('Component pouch', 1, 'Waives spell components that are not consumed by a spell. ', 25),
	('Crowbar', 1, 'If at first you dont succeed: Pry, pry again. ', 2),
	('Fishing tackle', 1, 'Check item description in player handbook', 1),
	('Flask or tankard', 1, 'Check item description in player handbook', 0.02),
	('Grappling hook', 1, 'Check item description in player handbook', 2),
	('Hammer', 1, 'Check item description in player handbook', 1),
	('Hammer, sledge', 1, 'Check item description in player handbook', 2),
	('Healers kit', 1, 'Check item description in player handbook', 5),
	('Holy water (flask)', 1, 'Check item description in player handbook', 25),
	('Hourglass', 1, 'Check item description in player handbook', 25),
	('Hunting trap', 1, 'Check item description in player handbook', 5),
	('Ink (1 ounce bottle)', 1, 'Check item description in player handbook', 10),
	('Ink pen', 1, 'Check item description in player handbook', 0.02),
	('Jug or pitcher', 1, 'Check item description in player handbook', 0.02),
	('Ladder (10 foot)', 1, 'Check item description in player handbook', 0.1),
	('Lamp', 1, 'Check item description in player handbook', 0.5),
	('Lantern, bullseye', 1, 'Check item description in player handbook', 10),
	('Lantern, hooded', 1, 'Check item description in player handbook', 5),
	('Lock', 1, 'Check item description in player handbook', 10),
	('Magnifying glass', 1, 'Check item description in player handbook', 100),
	('Manacles', 1, 'Check item description in player handbook', 2),
	('Mess kit', 1, 'Check item description in player handbook', 0.2),
	('Mirror, steel', 1, 'Check item description in player handbook', 5),
	('Oil (flask)', 1, 'Check item description in player handbook', 0.1),
	('Paper (one sheet)', 1, 'Check item description in player handbook', 0.2),
	('Parchment (one sheet)', 1, 'Check item description in player handbook', 0.1),
	('Perfume (vial)', 1, 'Check item description in player handbook', 5),
	('Pick, miners', 1, 'Check item description in player handbook', 2),
	('Piton', 1, 'Check item description in player handbook', 0.05),
	('Poison, basic (vial)', 1, 'Check item description in player handbook', 100),
	('Pole (10-foot)', 1, 'Check item description in player handbook', 0.05),
	('Pot, iron', 1, 'Check item description in player handbook', 2),
	('Potion of healing', 1, 'Check item description in player handbook', 50),
	('Pouch', 1, 'Check item description in player handbook', 0.5),
	('Quiver', 1, 'Check item description in player handbook', 1),
	('Ram, portable', 1, 'Check item description in player handbook', 4),
	('Rations (1 day)', 1, 'Check item description in player handbook', 0.5),
	('Robes', 1, 'Check item description in player handbook', 1),
	('Rope, hempen (50 feet)', 1, 'Check item description in player handbook', 1),
	('Rope, silk (50 feet)', 1, 'Check item description in player handbook', 10),
	('Sack', 1, 'Check item description in player handbook', 0.01),
	('Scale, merchants', 1, 'Check item description in player handbook', 5),
	('Sealing wax', 1, 'Check item description in player handbook', 0.5),
	('Shovel', 1, 'Check item description in player handbook', 2),
	('Signal whistle', 1, 'Check item description in player handbook', 0.05),
	('Signet ring', 1, 'Check item description in player handbook', 5),
	('Soap', 1, 'Check item description in player handbook', 0.02),
	('Spellbook', 1, 'Check item description in player handbook', 50),
	('Spikes, iron (10)', 1, 'Check item description in player handbook', 1),
	('Spyglass', 1, 'Check item description in player handbook', 1000),
	('Tent, two-person', 1, 'Check item description in player handbook', 2),
	('Tinderbox', 1, 'Check item description in player handbook', 0.5),
	('Torch', 1, 'Check item description in player handbook', 0.01),
	('Vial', 1, 'Check item description in player handbook', 1),
	('Waterskin', 1, 'Check item description in player handbook', 0.2),
	('Whetstone', 1, 'Check item description in player handbook', 0.01),
	-- 3. Scroll
	-- 4. Trinket
	-- 5. Furniture
	('Table', 5, 'A four-legged table. ', 1),
	('Armchair', 5, 'A cushioned, wide chair. ', 3),
	('Single Bed', 5, 'A functional single bed. ', 5),
	('Double Bed', 5, 'A bed fit for two humanoids (or about 1/2 a Fluffy)', 8),
	('Poster Bed', 5, 'A somewhat gradiose, four poster bed', 15),
	('Bench', 5, 'A low bench, fit to sit on. ', 2),
	('Bookshelf', 5, 'A tall bookshelf. ', 5),
	('Cabinet', 5, 'A functional set of storage. ', 6),
	('Counter', 5, 'A smooth surface for cooking or tinkering sits above some storage space. ', 6),
	('Candleabra', 5, 'It holds enough candles to keep the night away. ', 10),
	('Chandelier', 5, 'Dazzle your friends and foes alike with this ceiling fixture. ', 20),
	('Chair', 5, 'A four-legged chair. ', 0.5),
	('Lamp', 5, 'A free-standing lamp that gives off a warm light when fueled. ', 10),
	('Dresser', 5, 'For all your clothes and trinkets. ', 12),
	('Flooring', 5, 'For a change of pace. ', 10),
	('Sofa', 5, 'A wide cushioned sofa. ', 30),
	('Stool', 5, 'A three-legged stool. ', 1.5),
	('Wardrobe', 5, 'A imposing wardrobe, for your sunday best. ', 15),
	('Mirror', 5, ' A full length mirror. Look! Its you! ', 30),
	('Bathtub', 5, 'Filling may take a while but you would be the cleanest creature on the continent. ', 10),
	('Chest', 5, 'A functional chest, to be booby trapped at your leisure. ', 5),
	('Candle', 5, 'A small candle holder. ', 1),
	('Grandfather Clock', 5, 'It gives a sinister gong every hour. ', 30),
	('Sconce', 5, 'A wall mount for a oil lamp, or other light source. ', 6);